### ISSUE TITLE
Scroll bar is hidden when moving slider

### ISSUE THREAD

**Issue by RyanGosden** [kylewetton/image-compare-viewer#38]
Minor issue which causes the page to 'jump' to the hiding and showing of scrollbar. 

Edit: Looking at your src, it seems like this is deliberate. Is there a specific reason to why the scrollbar is disabled?

**Comment by j3ll3yfi5h** [comment]
Same issue here...

**Comment by j3ll3yfi5h** [comment]
Workaround here:
https://github.com/j3ll3yfi5h/image-compare-viewer/commit/516da11c52aac38469cad225735fc209d1479682

**Comment by kylewetton** [comment]
@RyanGosden @tobkum @j3ll3yfi5h 

The code is meant to keep your scrollbar offset in tact so that your layout doesn't jump. My layout doesn't jump on my end. I've just testing Windows and Mac across a range of browsers.

The reason for the body scroll lock is for mobile support, the page should remain fixed when you're interacting with the compare viewer with your finger. It will outright break vertical option if it doesn't lock.

What browsers / devices are you using that your layout is popping?

Does the demo pop for you?

https://image-compare-viewer.netlify.app/

**Comment by j3ll3yfi5h** [comment]
@kylewetton

If you add...
```
html {
    overflow-y: scroll;
}
```
...you will see the jumping as well.

I'm currently trying to find out, if scrollbars on `html`-elements are wrong and why or not...

**Comment by j3ll3yfi5h** [comment]
This issue is based on the used library https://github.com/willmcpo/body-scroll-lock 

Related (unresolved) issues are:
https://github.com/willmcpo/body-scroll-lock/issues/108
https://github.com/willmcpo/body-scroll-lock/issues/244
